ПР 2 урок и 3.1
js-tasks-ru/js-20200622_mikhail-m pull request #3
Opened 2020-06-30 17:34 UTC by maximusnet

Исправил 2 урок по вашим замечаниям. в третьем 3.1 ошибка в тесте  from “../solution” поменял на index.js

2020-06-30 17:40 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 03-objects-arrays-intro-to-testing/1-create-getter/index.spec.js — изменен
```

2020-07-01 11:45 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    if(obj.hasOwnProperty(arg))  arr[arg]=`${arg}`;
`hasOwnProperty` - не используется в связке с `for...of` - так как данный цикл перебирает только собственные свойства

также не экономьте на скобках в `if` конструкциях

2020-07-01 11:47 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  const arr = {};
данная переменная не может называться `arr` так как `arr` - это сокращение от "array" что означает "массив" 
а на деле в эту переменную присвоен объект - это собьет с толку ваших гипотетических коллег
пожалуйста переименуйте

2020-07-01 11:47 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    if(obj.hasOwnProperty(arg))  delete arr[arg];
`hasOwnProperty` см. комментарий выше

2020-07-01 11:48 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +export function sortStrings(arr, param = 'asc') {
пожалуйста посмотрите пример решения данной задачи который мы разбирали на занятии!

2020-07-01 11:48 UTC, dosandk approved these changes
с большой натяжкой решения принимаются, пожалуйста обращайте внимание на разбор решений заданий на занятии

Пожалуйста выполните следующие команды:

```
git pull fork master
git push origin master
```

2020-07-01 11:48 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-07-02 08:39 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings
+ should correctly sort language-specific characters
+ should correctly sort strings started from uppercase
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```
```diff
Первая задача
+ should return sum of numbers
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-07-02 08:43 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +      if (Object.keys(obj).length){ //пустой или нет
а если будет `path` состоять больше чем из 3х частей?
```
case 1 :
          return obj[patharr[0]];
        case 2 :
          return obj[patharr[0]][patharr[1]];
        case 3 :
          return obj[patharr[0]][patharr[1]][patharr[2]];
        }}
```
Вот этот кусок нужно подумать как сделать динамческим...

2020-07-02 08:45 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  let Sum = [];
эта задача решается в одну строчку
```
return [...new Set(...arr)];
```

2020-07-02 08:45 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +      if(elem in objSymbol) {objSymbol[elem] +=1;}
на скобочках в `if...else` не нужно экономить

2020-07-02 08:46 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +export function trimSymbols(string, size=1111) {
решение принимается - на занятии будем разбирать альтернативное решение

2020-07-02 08:48 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  //явный возврат undifiend для задачи
можно решить задачу чуть короче:
```
if (obj) {
    return  // ... logic
  }
```
если не попали в `if` то функция по умолчанию вернет `undefined`

2020-07-02 08:48 UTC, dosandk requested changes
Нужно поправить `createGetter` функцию, остальные задачи из модуля 3 принимаются

2020-07-04 14:18 UTC, jsru commented
@dosandk ping :)

2020-07-05 07:07 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    return  path.split(`.`)
`path.split('.')` - было бы неплохо выполнить данную операцию в родительской функции.
Почему? - пересмотрите пожалуйста разбор данной задачи на занятии

2020-07-05 07:08 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +           // console.log("Block acc[elem]",acc[elem]);
пожалуйста, удаляйте все лишние комментарии в коде перед отправкой пулл-реквеста - это хорошая практика, возьмите ее на вооружение

2020-07-05 07:11 UTC, dosandk commented
@maximusnet Пожалуйста еще раз посмотрите на функцию "createGetter" - которую разбирали на занятии и поправте коменты к ней

2020-07-05 14:29 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
ColumnChart компонент
- should be rendered correctly
- should have ability to define label
- should have ability to define link
- should have ability to define total value
- should have property 'chartHeight
- should render data correctly
- should have ability to be update by new values
- should have loading indication if data wasn't passed 
- should have ability to be removed
```
```diff
createGetter
+ should return "undefined" for properties which does not exist
+ returns undefined for no property
+ returns undefined for no nested.property
- should return existed properties
- gets obj.property
- gets obj.nested.property
- gets more.nested.property
```
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings
+ should correctly sort language-specific characters
+ should correctly sort strings started from uppercase
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```
```diff
Первая задача
+ should return sum of numbers
```

2020-07-06 11:54 UTC, dosandk approved these changes
Я апруваю и закрываю этот PR
Разбираться с ColumnChart будем в индивидуальном порядке, пока получается плохо

Пожалуйста внимательно сегодня посмотрите на разбор данного компонента

2020-07-06 11:54 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-07-06 12:37 UTC, maximusnet commented
Почему не проходит?

2020-07-06 15:34 UTC, jsru commented
@dosandk ping :)

2020-07-06 16:06 UTC, dosandk approved these changes
done

2020-07-06 16:06 UTC, merged