5.1 не понятно почему не проходит тест
js-tasks-ru/js-20200622_mikhail-m pull request #4
Opened 2020-07-12 13:50 UTC by maximusnet

05-dom-document-loading/1-notification/index.spec.js
  dom-document-loading/notification
    ✓ should be rendered correctly (102ms)
    ✓ should have ability to set duration (17ms)
    ✕ should be removed after time defined in duration property (180ms)
    ✓ should have ability to set message (7ms)
    ✓ should have ability to set 'success' type of message (14ms)
    ✓ should have ability to set 'error' type of message (3ms)
    ✕ should have ability to define target element for rendering  (11ms)
    ✓ should have ability to be destroyed (3ms)

2020-07-12 13:56 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-07-13 10:21 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
>  export default class NotificationMessage {
пожалуйста перед созданием PR форматируйте код, соблюдайте отступы

2020-07-13 10:21 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  durationInSeconds = 2;
это значение должно рассчитываться динамически на основе параметра `duration`

2020-07-13 10:22 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  message = null
`message` - это строка которую мы передаем в констрктор, поэтому было бы неплохо инициализировать ее пустой строкой вместо `null`

2020-07-13 10:23 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    type = 'success',}={}){
запятую - убрать

2020-07-13 10:23 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    this.durationInSeconds=(duration/1000)+ 's';;
точку с запятой в конце тоже убрать, оставить только одну

2020-07-13 10:23 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    console.log(`Before parent append - `, parent);
консолей в коде не должно быть

2020-07-13 10:24 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    console.log(`After parent append - ` ,parent.outerHTML);
перед отправкой PR, пожалуйста наводите в коде порядок:
* убедитесь что нет консолей
* убедитесь что код отформатирован, учтены пробелы и отступы

2020-07-13 10:25 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +
пустые линейки кода тоже необходимо убирать, следите за аккуратностью кода

2020-07-13 10:29 UTC, dosandk requested changes
Внесите изменения чтобы прошли тесты:
**"should have ability to define target element for rendering"** не проходит из-за вот этой строки:
`this.timerId = setTimeout(this.remove(),this.duration);` - вы теряете контекст выполнения при вызове `this.remove` - попробуйте исправить самостоятельно

**should be removed after time defined in duration property** - не проходит так как намудрили с методами `remove` и `destroy`
они должны выглядеть вот так
```
  remove() {
    this.element.remove();
  }

  destroy() {
    this.remove();
    NotificationMessage.activeNotification = null;
  }
```

2020-07-15 10:27 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-07-22 14:41 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort 'asc' correctly for 'sortType' equal string
+ should sort 'desc' correctly for 'sortType' equal string
+ should sort 'asc' correctly for 'sortType' equal number
+ should sort 'desc' correctly for 'sortType' equal number
+ should have ability to be destroyed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering 
+ should have ability to be destroyed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-07-24 12:31 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
>  export default class SortableTable {
good 👍

2020-07-24 12:31 UTC, dosandk approved these changes

2020-07-24 12:31 UTC, merged